// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhFMXrCVzos3Dmh_KWvZK9hz-K8gNEpfM',
    appId: '1:844787831155:web:55abd4096a9da7e29ef506',
    messagingSenderId: '844787831155',
    projectId: 'ukk2025isnaini',
    authDomain: 'ukk2025isnaini.firebaseapp.com',
    storageBucket: 'ukk2025isnaini.firebasestorage.app',
    measurementId: 'G-RB3DMR30LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOBv9NVUCEdiIllNrET6S9PmG4BaayHso',
    appId: '1:844787831155:android:68f05ea371e4ab129ef506',
    messagingSenderId: '844787831155',
    projectId: 'ukk2025isnaini',
    storageBucket: 'ukk2025isnaini.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsV2T8QbxPyvfsOSZ9TU2MTdxWAo7CFDs',
    appId: '1:844787831155:ios:6ad40b7b0bfd07e39ef506',
    messagingSenderId: '844787831155',
    projectId: 'ukk2025isnaini',
    storageBucket: 'ukk2025isnaini.firebasestorage.app',
    iosBundleId: 'com.example.ukkIsnaini2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsV2T8QbxPyvfsOSZ9TU2MTdxWAo7CFDs',
    appId: '1:844787831155:ios:6ad40b7b0bfd07e39ef506',
    messagingSenderId: '844787831155',
    projectId: 'ukk2025isnaini',
    storageBucket: 'ukk2025isnaini.firebasestorage.app',
    iosBundleId: 'com.example.ukkIsnaini2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhFMXrCVzos3Dmh_KWvZK9hz-K8gNEpfM',
    appId: '1:844787831155:web:8570cc4be0f997279ef506',
    messagingSenderId: '844787831155',
    projectId: 'ukk2025isnaini',
    authDomain: 'ukk2025isnaini.firebaseapp.com',
    storageBucket: 'ukk2025isnaini.firebasestorage.app',
    measurementId: 'G-H34Q28RTS9',
  );
}
